2020/BancoNoSQL/app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'carrinho#index'
  resources :carrinho, only: [:index, :edit, :new, :destroy, :create, :update]

  post "carrinho/:id/edit", to:"carrinho#update", as: "carrinho_edit"
  post "carrinho/:id/destroy", to:"carrinho#destroy", as: "carrinho_destroy"
  
end

2020/BancoNoSQL/app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

2020/BancoNoSQL/app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

2020/BancoNoSQL/app/app/controllers/carrinho_controller.rb
require "redis"
require "json"
class CarrinhoController < ApplicationController
  def index
    redis = Redis.new
    @all_products_keys = redis.keys('*')
    @list_products = []
    if @all_products_keys.count() > 0
      @all_products_values = redis.mget(@all_products_keys)
      (0..@all_products_values.count()-1).each do |index|
        product = @all_products_values[index]
        product = product.remove("\\")
        @list_products.push({@all_products_keys[index] =>  JSON.parse(product)})
      end
      @list_products
    end
  end


  def new
    redis = Redis.new
    list_keys = redis.keys('*').sort
    count_docs = list_keys.pop.to_i + 1
    redis.set(count_docs, [permited_params[:nome_produto], permited_params[:preco]])
    redirect_to root_path
  end
  def create
  end 

  def edit
  end

  def update 
    redis = Redis.new
    redis.set(permited_params[:id], [permited_params[:nome_produto], permited_params[:preco]])
    redirect_to root_path
  end


  def destroy
    redis = Redis.new
    redis.del(permited_params[:id])
    redirect_to root_path
  end

  private
  def permited_params
    params.permit(:nome_produto, :preco, :id)
  end
end

2020/BancoNoSQL/app/app/helpers/application_helper.rb
module ApplicationHelper
end

2020/BancoNoSQL/app/app/views/carrinho/create.html.erb
<%= form_tag new_carrinho_path, :method => 'get' do%>
  <div class="row justify-content-center m-5">
    <h3>Inserir produto</h3>
  </div>
  <div class="row justify-content-center m-5">
    <div class="col-md-5">
      <%= text_field_tag :nome_produto, params[:nome_produto], :class => 'form-control', :placeholder => 'Nome produto'%>
    </div>
    <div class="col-md-5">
      <%= text_field_tag :preco, params[:preco], :class => 'form-control', :placeholder => 'Preço'%>
    </div>
  </div>
  <div class="row justify-content-center m-5">
    <%= submit_tag "Add produto", :name => nil, :class => "btn btn-info"%>
  </div>
<% end %>

2020/BancoNoSQL/app/app/views/carrinho/edit.html.erb
<%= form_tag carrinho_edit_path(params[:id]), method: :post do%>
  <div class="row justify-content-center m-5">
    <h3>Editar produto</h3>
  </div>
  <div class="row justify-content-center m-5">
    <div class="col-md-5">
      <%= text_field_tag :nome_produto, params[:nome_produto], :class => 'form-control', :placeholder => 'Nome produto'%>
    </div>
    <div class="col-md-5">
      <%= text_field_tag :preco, params[:preco], :class => 'form-control', :placeholder => 'Preço'%>
    </div>
  </div>
  <div class="row justify-content-center m-5">
    <%= submit_tag "edit produto", :name => nil, :class => "btn btn-info"%>
  </div>
<% end %>

2020/BancoNoSQL/app/app/views/carrinho/index.html.erb
<%= form_tag new_carrinho_path, :method => 'get' do%>
  <div class="row justify-content-center m-5">
    <h3>Inserir produto</h3>
  </div>
  <div class="row justify-content-center m-5">
    <div class="col-md-5">
      <%= text_field_tag :nome_produto, params[:nome_produto], :class => 'form-control', :placeholder => 'Nome produto'%>
    </div>
    <div class="col-md-5">
      <%= text_field_tag :preco, params[:preco], :class => 'form-control', :placeholder => 'Preço'%>
    </div>
  </div>
  <div class="row justify-content-center m-5">
    <%= submit_tag "Add produto", :name => nil, :class => "btn btn-info"%>
  </div>
<% end %>
<hr/>
  <div class="row justify-content-center m-5">
    <h3>Lista de produto</h3>
  </div>
<%if @all_products_keys.count() != 0%>
  <div class="row justify-content-center m-5">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">Produto</th>
          <th scope="col">Preço</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @list_products.each do |product| %>
          <tr>
              <% product.each do |value| %>
                <td><%= value[0] %></td>
                <td><%= value[1][0] %></td>
                <td><%= value[1][1] %></td>
                <td>
                  <%= button_to 'Editar', edit_carrinho_path(value[0]) , method: :get, class: "btn btn-success" %>
                </td>
                <td>
                  <%= button_to 'Delete', carrinho_destroy_path(value[0]) , method: :post, class: "btn btn-danger" %>
                </td>
              <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<%else%>
  <div class="row justify-content-center m-5">
    <h4> Lista vazia</h4>
  </div>
<% end %>

2020/BancoNoSQL/app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>